# Generated by Django 2.2.1 on 2019-07-19 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('room', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('file', models.CharField(max_length=2048)),
                ('score', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=160)),
                ('gender', models.CharField(max_length=1)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Class')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.ProjectPool')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.User')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deadline', models.PositiveIntegerField()),
                ('create_time', models.PositiveIntegerField()),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Doc')),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='mission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Mission'),
        ),
    ]
