# Generated by Django 2.2.1 on 2019-07-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190720_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
