# Generated by Django 2.2.2 on 2019-07-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190721_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exist',
            field=models.BooleanField(default=True),
        ),
    ]
