"""
Django settings for TMS project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1-+za8sb5hlc#tl^_%62!yvoi1q&z)o*9ynce40i=^^zxj7g)b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'database',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 在开发初期,屏蔽csrf中间件
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # @Lizhenghao
    # 设置mysql数据库
    # 2019年07月16日10:05:53
    #########################
    # @Lizhenghao
    # 重新配置mysql数据库,更新至腾讯云数据库
    # 2019-07-20 08:47:37
    'default': {
        # 数据库引擎名称, 此处使用MySQL
        'ENGINE': 'django.db.backends.mysql',
        # 数据库名称,与数据库内部有关
        'NAME': 'django_TMS',
        # 数据库用户名,敏感信息,不要轻易暴露
        'USER': 'user_TMS',
        # 数据库密码,敏感信息,不要轻易暴露
        'PASSWORD': 'qweqwe123',
        # 数据库所在地址,若数据库在本地则使用localhost
        # 'HOST': 'cd-cdb-5w9d2w14.sql.tencentcdb.com',
        'HOST': 'rm-wz990kv1561j1bfh7.mysql.rds.aliyuncs.com',
        # 数据库端口号,MySQL默认使用3306号
        # 'PORT': '62949',
        'PORT': '3306',
        # 设置mysql严格模式
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# STATIC_URL = '/static/'


# Personal Settings

# 设置路由路径,静态文件的映射路径
# 在模板中访问静态文件时,{% static '<静态文件路径>' %}会指向该路由
STATIC_URL = '/static/'
# 执行`python manage.py collectstatic`时静态文静聚合的目录
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# 公有资源
PUBLIC_ROOT = os.path.join(BASE_DIR, 'public/')

# 设置媒体文件路由路径
MEDIA_URL = '/media/'
# 设置静态媒体文件路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 设置文稿池路径
FILE_ROOT = os.path.join(MEDIA_ROOT, 'file/')

# 设置会话缓存策略
SESSION_SAVE_EVERY_REQUEST = True
# 设置会话30分钟有效
SESSION_COOKIE_AGE = 60 * 30
# 关闭浏览器，则COOKIE失效
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
